// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'zh-tw'

export type Locales =
	| 'zh-tw'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * 繁​體​中​文
	 */
	name: string
	navbar: {
		/**
		 * 新​樓​醫​院​心​臟​科​附​屬
		 */
		title: string
		/**
		 * 臺​南​一​中​電​機​社
		 */
		name: string
		/**
		 * L​i​g​h​t​ ​T​h​e​m​e
		 */
		lightTheme: string
		/**
		 * D​a​r​k​ ​T​h​e​m​e
		 */
		darkTheme: string
		/**
		 * L​a​n​g​u​a​g​e
		 */
		language: string
		/**
		 * S​i​g​n​ ​I​n
		 */
		signIn: string
		/**
		 * S​i​g​n​ ​O​u​t
		 */
		signOut: string
		/**
		 * S​i​g​n​e​d​ ​i​n​ ​a​s
		 */
		signedInAs: string
		/**
		 * N​e​w​ ​P​o​s​t
		 */
		newPost: string
	}
	home: {
		/**
		 * 電​�​�​社
		 */
		name: string
		/**
		 * 你​說​得​對​，​但​是​電​機​社​的​常​住​人​口​有​十​幾​人​，​同​時​，​僅​澳​大​利​亞​就​有​4​7​0​0​萬​隻​袋​鼠​。​如​果​袋​鼠​決​定​入​侵​4​0​3​，​那​麼​每​一​個​電​機​社​員​要​打​3​百​萬​只​袋​鼠​，​你​不​知​道​，​你​不​在​乎​，​你​只​關​心​你​自​己​。
		 */
		description: string
		/**
		 * 電​機​社​！​啟​動​！​嘻​嘻​嘻​嘻​嘻​！​我​最​喜​歡​玩​機​器​了​，​我​是​ ​A​r​d​u​i​n​o​ ​玩​家​！​你​看​這​是​我​新​買​的​模​組​～​蜂​鳴​器​！​！​蹦​蹦​喇​叭​～
		 */
		quote: string
		/**
		 * 更​多​資​訊
		 */
		moreInfo: string
		news: {
			/**
			 * 最​新​消​息
			 */
			name: string
			/**
			 * 你​好​，​我​是​狒​狒​，​目​前​在​中​国​台​湾​桃​园​市​六​福​村​附​近​山​区​，​刚​刚​突​然​开​始​下​大​雷​雨​，​我​急​需​钱​买​雨​具​，​若​我​日​后​逃​脱​成​功​，​必​有​钜​额​回​报​，​你​可​以​帮​帮​我​吗​？​请​加​L​i​n​e​：​8​7​8​7​8​7​8​7​m​o​n​k​e​y​，​谢​谢​！
			 */
			description: string
			/**
			 * 查​看​其​他
			 */
			other: string
		}
		interests: {
			/**
			 * 社​團​活​動
			 */
			name: string
			/**
			 * 應​該​永​遠​不​會​去​玩​了​�​�​�​�​
		​好​歹​我​也​是​G​o​o​g​l​e​地​圖​6​級​在​地​導​覽​�​�​
		​專​業​攝​影​師​�​�​專​業​評​論​家​�​�​‍​�​�​�​�​�​�​�​�​
		​剛​剛​發​現​社​團​的​態​度​是​這​樣​�​�​�​�​
		​人​家​沒​混​成​�​�​�​�​�​�​還​想​得​星​星​�​�​�​�​
		​還​放​在​粉​絲​團​公​審​�​�​�​�​
		​難​怪​我​們​社​課​的​時​候​看​地​圖​評​論​覺​得​很​納​悶​�​�​�​�​
		​為​什​麼​評​論​會​這​麼​兩​極​化​�​�​�​�
			 */
			description: string
			/**
			 * 機​器​人
			 */
			robot: string
			/**
			 * 區​區​幾​個​人​類​…​我​一​個​一​個​ㄅ​ㄧ​ㄢ​ˇ
			 */
			robotDescription: string
			/**
			 * 硬​體
			 */
			hardware: string
			/**
			 * 據​說​社​部​沒​有​電​池​？
			 */
			hardwareDescription: string
			/**
			 * 軟​體​ ​/​ ​網​頁
			 */
			software: string
			/**
			 * 還​是​ ​J​S​ ​最​棒​了​！​（​X
			 */
			softwareDescription: string
			/**
			 * 你​的​興​趣​！
			 */
			others: string
			/**
			 * 我​們​讓​你​將​熱​情​消​耗​殆​盡​~​（​好​的​方​面​）
			 */
			othersDescription: string
		}
		comments: {
			/**
			 * 大​家​都​說​…
			 */
			name: string
		}
	}
	postList: {
		/**
		 * 最​新​消​息
		 */
		name: string
		/**
		 * 
	​在​電​梯​遇​到​了​一​個​女​生​
	​她​對​我​笑​了​一​下​
	​按​下​了​第​8​層​
	​呵​ ​真​會​暗​示​
	​她​8​層​有​點​喜​歡​我​吧​
	​但​我​是​不​會​暈​的​ ​(​ゝ​∀​･​)​⌒​☆​

		 */
		description: string
	}
	post: {
		/**
		 * P​i​n​n​e​d
		 */
		pinned: string
		/**
		 * B​y​ ​{​0​}
		 * @param {string} 0
		 */
		postedBy: RequiredParams<'0'>
		/**
		 * O​n​ ​T​h​i​s​ ​P​a​g​e
		 */
		tableOfContents: string
		/**
		 * E​d​i​t
		 */
		edit: string
	}
	postEdit: {
		name: string
		/**
		 * S​a​v​e
		 */
		save: string
		/**
		 * D​e​l​e​t​e
		 */
		'delete': string
		/**
		 * Y​o​u​'​r​e​ ​d​e​l​e​t​i​n​g​ ​t​h​i​s​ ​p​o​s​t​,​ ​c​o​n​f​i​r​m​ ​w​i​t​h​ ​c​a​u​t​i​o​n​!​
	​T​h​e​ ​p​o​s​t​ ​a​i​n​'​t​ ​c​o​m​i​n​g​ ​b​a​c​k​ ​a​f​t​e​r​ ​t​h​i​s​!
		 */
		deleteConfirmation: string
		/**
		 * C​a​n​c​e​l
		 */
		dialogCancel: string
		/**
		 * C​o​n​f​i​r​m
		 */
		dialogConfirm: string
		/**
		 * P​o​s​t​ ​i​s​ ​S​a​v​e​d
		 */
		saveMessage: string
		/**
		 * P​o​s​t​ ​D​e​l​e​t​e​d
		 */
		deleteMessage: string
		field: {
			/**
			 * U​R​L
			 */
			url: string
			/**
			 * T​i​t​l​e
			 */
			title: string
			/**
			 * A​u​t​h​o​r
			 */
			author: string
			/**
			 * D​a​t​e
			 */
			date: string
			/**
			 * I​m​a​g​e
			 */
			image: string
			/**
			 * D​e​s​c​r​i​p​t​i​o​n
			 */
			description: string
			/**
			 * P​i​n​n​e​d
			 */
			pinned: string
		}
	}
}

export type TranslationFunctions = {
	/**
	 * 繁體中文
	 */
	name: () => LocalizedString
	navbar: {
		/**
		 * 新樓醫院心臟科附屬
		 */
		title: () => LocalizedString
		/**
		 * 臺南一中電機社
		 */
		name: () => LocalizedString
		/**
		 * Light Theme
		 */
		lightTheme: () => LocalizedString
		/**
		 * Dark Theme
		 */
		darkTheme: () => LocalizedString
		/**
		 * Language
		 */
		language: () => LocalizedString
		/**
		 * Sign In
		 */
		signIn: () => LocalizedString
		/**
		 * Sign Out
		 */
		signOut: () => LocalizedString
		/**
		 * Signed in as
		 */
		signedInAs: () => LocalizedString
		/**
		 * New Post
		 */
		newPost: () => LocalizedString
	}
	home: {
		/**
		 * 電🐔社
		 */
		name: () => LocalizedString
		/**
		 * 你說得對，但是電機社的常住人口有十幾人，同時，僅澳大利亞就有4700萬隻袋鼠。如果袋鼠決定入侵403，那麼每一個電機社員要打3百萬只袋鼠，你不知道，你不在乎，你只關心你自己。
		 */
		description: () => LocalizedString
		/**
		 * 電機社！啟動！嘻嘻嘻嘻嘻！我最喜歡玩機器了，我是 Arduino 玩家！你看這是我新買的模組～蜂鳴器！！蹦蹦喇叭～
		 */
		quote: () => LocalizedString
		/**
		 * 更多資訊
		 */
		moreInfo: () => LocalizedString
		news: {
			/**
			 * 最新消息
			 */
			name: () => LocalizedString
			/**
			 * 你好，我是狒狒，目前在中国台湾桃园市六福村附近山区，刚刚突然开始下大雷雨，我急需钱买雨具，若我日后逃脱成功，必有钜额回报，你可以帮帮我吗？请加Line：87878787monkey，谢谢！
			 */
			description: () => LocalizedString
			/**
			 * 查看其他
			 */
			other: () => LocalizedString
		}
		interests: {
			/**
			 * 社團活動
			 */
			name: () => LocalizedString
			/**
			 * 應該永遠不會去玩了😡😡
		好歹我也是Google地圖6級在地導覽📌
		專業攝影師📷專業評論家👨‍🍳😳😳😳
		剛剛發現社團的態度是這樣😫😫
		人家沒混成😭😭😭還想得星星😅😅
		還放在粉絲團公審😂🤬
		難怪我們社課的時候看地圖評論覺得很納悶😱😰
		為什麼評論會這麼兩極化🥺😒
			 */
			description: () => LocalizedString
			/**
			 * 機器人
			 */
			robot: () => LocalizedString
			/**
			 * 區區幾個人類…我一個一個ㄅㄧㄢˇ
			 */
			robotDescription: () => LocalizedString
			/**
			 * 硬體
			 */
			hardware: () => LocalizedString
			/**
			 * 據說社部沒有電池？
			 */
			hardwareDescription: () => LocalizedString
			/**
			 * 軟體 / 網頁
			 */
			software: () => LocalizedString
			/**
			 * 還是 JS 最棒了！（X
			 */
			softwareDescription: () => LocalizedString
			/**
			 * 你的興趣！
			 */
			others: () => LocalizedString
			/**
			 * 我們讓你將熱情消耗殆盡~（好的方面）
			 */
			othersDescription: () => LocalizedString
		}
		comments: {
			/**
			 * 大家都說…
			 */
			name: () => LocalizedString
		}
	}
	postList: {
		/**
		 * 最新消息
		 */
		name: () => LocalizedString
		/**
		 * 
	在電梯遇到了一個女生
	她對我笑了一下
	按下了第8層
	呵 真會暗示
	她8層有點喜歡我吧
	但我是不會暈的 (ゝ∀･)⌒☆

		 */
		description: () => LocalizedString
	}
	post: {
		/**
		 * Pinned
		 */
		pinned: () => LocalizedString
		/**
		 * By {0}
		 */
		postedBy: (arg0: string) => LocalizedString
		/**
		 * On This Page
		 */
		tableOfContents: () => LocalizedString
		/**
		 * Edit
		 */
		edit: () => LocalizedString
	}
	postEdit: {
		name: () => LocalizedString
		/**
		 * Save
		 */
		save: () => LocalizedString
		/**
		 * Delete
		 */
		'delete': () => LocalizedString
		/**
		 * You're deleting this post, confirm with caution!
	The post ain't coming back after this!
		 */
		deleteConfirmation: () => LocalizedString
		/**
		 * Cancel
		 */
		dialogCancel: () => LocalizedString
		/**
		 * Confirm
		 */
		dialogConfirm: () => LocalizedString
		/**
		 * Post is Saved
		 */
		saveMessage: () => LocalizedString
		/**
		 * Post Deleted
		 */
		deleteMessage: () => LocalizedString
		field: {
			/**
			 * URL
			 */
			url: () => LocalizedString
			/**
			 * Title
			 */
			title: () => LocalizedString
			/**
			 * Author
			 */
			author: () => LocalizedString
			/**
			 * Date
			 */
			date: () => LocalizedString
			/**
			 * Image
			 */
			image: () => LocalizedString
			/**
			 * Description
			 */
			description: () => LocalizedString
			/**
			 * Pinned
			 */
			pinned: () => LocalizedString
		}
	}
}

export type Formatters = {}
