name: AutoCorrect Lint

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Lint with AutoCorrect and report
        uses: huacnlee/autocorrect-action@v2
        env: 
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: --lint $(git diff --diff-filter=AM --name-only ${{ github.event.pull_request.base.sha }})
          reviewdog: true
