name: Deploy to GitHub Pages

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  build_site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # If you're using pnpm, add this step then change the commands and cache key below to use `pnpm`
      # - name: Install pnpm
      #   uses: pnpm/action-setup@v2
      #   with:
      #     version: 8

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Create .env file
        run: |
          touch .env
          echo AUTH_SECRET=${{ secrets.AUTH_SECRET }} >> .env
          echo GITHUB_ID="" >> .env
          echo GITHUB_SECRET="" >> .env
          echo ADMINS="" >> .env

      - name: build
        env:
          PRERENDER: true
          AUTH_TRUST_HOST: true
          BASE_PATH: "/tnfshcec-web"
        run: |
          npm run build
          touch build/.nojekyll

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v1
        with:
          # this should match the `pages` option in your adapter-static options
          path: "build/"

  deploy:
    if: ${{ github.event_name != 'pull_request' }}
    needs: build_site
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v1
